name: Build and deploy Python app on azure 

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Set up Python versionSpec
      uses: actions/setup-python@v4
      with: 
        python-version: '3.13'

    - name: Create Venv
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Set up cache dependency
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: install dependencies
      run: pip install -r requirements.txt

    - name: 'Deploy to azure web app'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with: 
        app-name: meu-app-pipeline
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
        package: .
